version: '3'

services:
  web:
    restart: always
    image: explain:latest
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      DB_SERVICE: postgres

  migrate:
    restart: "no"
    image: explain:latest
    command:
      - "flask"
      - "db"
      - "upgrade"
    environment:
      DB_SERVICE: postgres

  postgres:
    restart: always
    image: postgres:latest
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres

volumes:
  db-data:
